version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build  # if applicable
      - run: npx @azure/static-web-apps-cli deploy ./dist --deployment-token $AZURE_SWA_TOKEN
      
      
#workflows:
  #deploy-frontend:
    #jobs:
      #- build:
        #  filters:
          #  branches:
            #  only:
              #  - circleci-project-setup
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
